name: Scheduled Trigger Contests
on:
  schedule:
    - cron: '17 3 * * 0' # Weekly Contest: Sunday at 4:00 AM GMT (2:30 AM + 1.5 hours) minus 43 minutes scheduler gap
    - cron: '17 15 * * 6' # Biweekly Contest: Saturday at 4:00 PM GMT (2:30 PM + 1.5 hours) minus 43 minutes scheduler gap
  workflow_dispatch:

jobs:
  trigger-update:
    uses: ./.github/workflows/update-data-contests.yml
