name: Scheduled Trigger Contests
on:
  schedule:
    - cron: '00 4 * * 0' # Weekly Contest: Sunday at 4:00 AM GMT (2:30 AM + 1.5 hours)
    - cron: '00 16 * * 6' # Biweekly Contest: Saturday at 4:00 PM GMT (2:30 PM + 1.5 hours)
  workflow_dispatch:

jobs:
  trigger-update:
    uses: ./.github/workflows/update-data-contests.yml
