name: Scheduled Trigger
on:
  schedule:
    - cron: '43 23 * * *' # 00:00 GMT minus 17 minutes scheduler gap (runs at about 00:15 GMT)
  workflow_dispatch:

jobs:
  trigger-update:
    uses: ./.github/workflows/update-data.yml
