name: Scheduled Trigger
on:
  schedule:
    - cron: '30 0 * * *'  # 00:30 GMT daily
  workflow_dispatch:

jobs:
  trigger-update:
    uses: ./.github/workflows/update-data.yml  # Calls the reusable workflow
